version: '3.7'

services:
  sw-editor:
    image: swaggerapi/swagger-editor
    container_name: sw_editor
    tty: true
    ports:
      - 16000:8080
    environment:
      - BASE_URL=/
      - SWAGGER_FILE=/tmp/swagger.yaml
    # volumes:
    #   - ./swagger.yaml:/tmp/swagger.yaml

  sw-ui:
    image: swaggerapi/swagger-ui
    container_name: sw_ui
    tty: true
    ports:
      - 16001:8080
    environment:
      - SWAGGER_JSON=/tmp/swagger.yaml
    volumes:
      - ./swagger.yaml:/tmp/swagger.yaml

  db:
    image: mysql:5.7
    container_name: tutorial_mysql
    tty: true
    ports:
      - 16002:3306
    command: mysqld --character-set-server=utf8 --collation-server=utf8_unicode_ci
    volumes:
      # - ./db/init:/docker-entrypoint-initdb.d
      - tutorial-db-volume:/var/lib/mysql
    environment:
      - MYSQL_DATABASE=tutorial
      - MYSQL_ROOT_PASSWORD=password

volumes:
  tutorial-db-volume: